//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRobotServer.RobotActions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotActions.IRobot", CallbackContract=typeof(WpfRobotServer.RobotActions.IRobotCallback))]
    public interface IRobot {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/GetWindow")]
        void GetWindow(string windowTitle);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/GetWindow")]
        System.Threading.Tasks.Task GetWindowAsync(string windowTitle);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/MoveMouse")]
        void MoveMouse(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/MoveMouse")]
        System.Threading.Tasks.Task MoveMouseAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/MouseCLick")]
        void MouseCLick();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/MouseCLick")]
        System.Threading.Tasks.Task MouseCLickAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/SetText")]
        void SetText(string text);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/SetText")]
        System.Threading.Tasks.Task SetTextAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRobot/CallBackGetWindow")]
        void CallBackGetWindow(string actionScript);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotChannel : WpfRobotServer.RobotActions.IRobot, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotClient : System.ServiceModel.DuplexClientBase<WpfRobotServer.RobotActions.IRobot>, WpfRobotServer.RobotActions.IRobot {
        
        public RobotClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RobotClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RobotClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RobotClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RobotClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetWindow(string windowTitle) {
            base.Channel.GetWindow(windowTitle);
        }
        
        public System.Threading.Tasks.Task GetWindowAsync(string windowTitle) {
            return base.Channel.GetWindowAsync(windowTitle);
        }
        
        public void MoveMouse(int x, int y) {
            base.Channel.MoveMouse(x, y);
        }
        
        public System.Threading.Tasks.Task MoveMouseAsync(int x, int y) {
            return base.Channel.MoveMouseAsync(x, y);
        }
        
        public void MouseCLick() {
            base.Channel.MouseCLick();
        }
        
        public System.Threading.Tasks.Task MouseCLickAsync() {
            return base.Channel.MouseCLickAsync();
        }
        
        public void SetText(string text) {
            base.Channel.SetText(text);
        }
        
        public System.Threading.Tasks.Task SetTextAsync(string text) {
            return base.Channel.SetTextAsync(text);
        }
    }
}
